### ISSUE TITLE
not work with spring-boot-1.4.2

### ISSUE THREAD

**Issue by thm1118** [ulisesbocchio/spring-boot-jar-resources-samples#1]
`java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at com.github.ulisesbocchio.SpringBootJarResourcesDemoApplication.main(SpringBootJarResourcesDemoApplication.java:34) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_102]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-boot-jar-resources-demo-1.2-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-boot-jar-resources-demo-1.2-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-boot-jar-resources-demo-1.2-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [spring-boot-jar-resources-demo-1.2-SNAPSHOT.jar:na]
Caused by: org.apache.commons.vfs2.FileSystemException: Could not replicate "file:///D:/works/javatest/spring-boot-jar-resources-samples/spring-boot-jar-resources-demo/target/spring-boot-jar-resources-demo-1.2-SNAPSHOT.jar!/BOOT-INF/classes" as it does not exist.
        at org.apache.commons.vfs2.provider.AbstractFileSystem.replicateFile(AbstractFileSystem.java:417) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.provider.zip.ZipFileSystem.<init>(ZipFileSystem.java:66) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.provider.jar.JarFileSystem.<init>(JarFileSystem.java:48) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.provider.jar.JarFileProvider.doCreateFileSystem(JarFileProvider.java:80) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:87) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:61) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:760) ~[commons-vfs2-2.1.jar!/:2.1]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:709) ~[commons-vfs2-2.1.jar!/:2.1]
        at com.github.ulisesbocchio.jar.resources.JarUtils.getFromJar(JarUtils.java:43) ~[spring-boot-jar-resources-1.2.jar!/:na]
        at com.github.ulisesbocchio.jar.resources.JarUtils.getFile(JarUtils.java:33) ~[spring-boot-jar-resources-1.2.jar!/:na]
        at com.github.ulisesbocchio.jar.resources.JarResource.getFile(JarResource.java:60) ~[spring-boot-jar-resources-1.2.jar!/:na]
        at com.github.ulisesbocchio.SpringBootJarResourcesDemoApplication.run(SpringBootJarResourcesDemoApplication.java:43) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        ... 12 common frames omitted`

**Comment by ulisesbocchio** [comment]
Alright, I'll take a look

**Comment by ulisesbocchio** [comment]
This is fixed in version 1.3 which I just released. Enjoy!

**Comment by thm1118** [comment]
Thanks for upgrading get it right so fast. work now
